language: node_js
node_js:
  - "14"
arch:
  - amd64
  - arm64
os:
  - linux
  - osx
before_deploy:
  - ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-$(uname -m).tar"
  - npm run prebuild
  - tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds" .
deploy:
  provider: releases
  api_key:
    secure: invalid
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
    node: "14"
